// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPOqxVUrElvthTM0XyhIEbGYGbo78VJY',
    appId: '1:1032918260053:web:3b2fc0c255da4c4a0fb7dc',
    messagingSenderId: '1032918260053',
    projectId: 'virusvalidate',
    authDomain: 'virusvalidate.firebaseapp.com',
    storageBucket: 'virusvalidate.appspot.com',
    measurementId: 'G-D1GQVP4PZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfsMYE4vNhCiakVfdgs9rJhKUCXrZ8f0',
    appId: '1:1032918260053:android:178392d41f7097580fb7dc',
    messagingSenderId: '1032918260053',
    projectId: 'virusvalidate',
    storageBucket: 'virusvalidate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBez1sFxbf7wz1FrSBj9NOK1XUB9s3RQtQ',
    appId: '1:1032918260053:ios:cecceed5073b29620fb7dc',
    messagingSenderId: '1032918260053',
    projectId: 'virusvalidate',
    storageBucket: 'virusvalidate.appspot.com',
    iosClientId: '1032918260053-kjlf8gsr55rt23hhe8b2pngv2nq7rodn.apps.googleusercontent.com',
    iosBundleId: 'com.example.virusValidate',
  );
}
